test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - nosetests tests/

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install curl
  - curl -X POST https://readthedocs.org/build/lang-gamification-api
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - curl -L https://get.rvm.io | bash -s stable
  - source /etc/profile.d/rvm.sh
  - rvm requirements
  - rvm install ruby
  - rvm use ruby --default
  - rvm rubygems current
  - gem install dpl
  - dpl --provider=heroku --app=lang-gamification-api --api-key=$HEROKU_API_KEY
  only:
  - master
