test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - curl --silent --location https://deb.nodesource.com/setup_0.12 | bash -
  - apt-get install -y nodejs
  - apt-get install -y build-essential
  - npm explore npm -g -- npm install node-gyp@latest
  - npm install newman
  - newman -u https://www.getpostman.com/collections/923ee38bcbb3ce825318 -e ./lang-gamification-api.postman_environment -s
  - pip install -r requirements.txt
  - nosetests tests/

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install curl
  - curl -X POST https://readthedocs.org/build/lang-gamification-api
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - curl -L https://get.rvm.io | bash -s stable
  - source /etc/profile.d/rvm.sh
  - rvm requirements
  - rvm install ruby
  - rvm use ruby --default
  - rvm rubygems current
  - gem install dpl
  - dpl --provider=heroku --app=lang-gamification-api --api-key=$HEROKU_API_KEY
  only:
  - master
