test:
  script:
  - export MONGODB_URL=mongodb://postgres:@postgres:5432/python-test-app
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - nosetests tests/

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=lang-gamification-api --api-key=$HEROKU_API_KEY
  only:
  - master