language: python
python:
- '2.7'
- '3.5'
install: pip install -r requirements.txt
script:
- export PYTHONPATH=`pwd`
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: "Cgvfphzq8Oh0jX2myRsohynwwj/Hmg5EkEEhslPwZf/Qwc9jKRky8ucE/hziQ8YiU2xOPFyd2LYICvQKZs4s4qqiNLGgsb1z0/5WFqzdZYLCjKcKluK9ChYnmC/Ykt2SHLrk+jF3fWhg8At5mZMQBD/5EoJO/ooAbQGxCbRVPIxfz9ksQHVY3Q4tYSzxHpb32MEe8tItufSmtLcIGwmRjkXts44h3WHmsedvQvJvlxWrhnPNJLc/5OORPBwR3ELaYHnEtxicbsBDuT/N8SWLBy6YNd5qlXfx3kUBxq2jH5YO35J3+4/HoQqxb+Kwsz6jRVcISWaVU2hNsMfxZD+ubminwr10ha8v9qAdJzouME2AQ3cG7uIuUX5gnHUfNnyaWf48NJPKFL+YrBzfheiaW0RvAOT2EsiWxcIR5CtydHk/+9r8DbW/29Y2JByE7xY9/q3ms7u4auhZsbIA5wt8fQsaHNfy5zcBeWIgUKUW9fd0P9mXlLNnMbwv6InBvGIXXeP7A7BnL7d/53f5rzm0gtO/A2WRs6ov2YiC/7WrcRPRLP3OYpBal6zR+KiT/J4qTtZ9euCVBYh3G9O+Fh49uNKZ1gPLOX9KrrOMSBM5hNX+mNDJPeMngnmijc05H/ET9oo+nTLVNOriQnkvbJgGn/F3t9f/2QnTQdPD38OdAYU="
  app: lang-gamification-api
  on:
    repo: jslvtr/lang-gamification-api
branches:
  only:
    - master